### ISSUE TITLE
Possible Segmentation Fault in try_dequeue

### ISSUE THREAD

**Issue by Zenohate** [cameron314/concurrentqueue#91]
I don't really get what made it happen, I would be glad if you could tell me if you can reproduce the bug with some code simpler than mine.

I added comments in my code to explain what happens, comments include stack trace with debug info and detailed compiler version (g++ 6.3.0 Linux 32bits)
[IssueMoodyCamel.zip](https://github.com/cameron314/concurrentqueue/files/1316148/IssueMoodyCamel.zip)

**Comment by Zenohate** [comment]
The very same behaviour is observable with CLang on the same platform 

`clang -g -std=c++14 -lstdc++ -lpthread -I. Pipeline.cpp`

```
Thread 2 "a.out" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb7be1b40 (LWP 16857)]
0x0804bcad in std::__atomic_base<moodycamel::ConcurrentQueue<int, moodycamel::ConcurrentQueueDefaultTraits>::ProducerBase*>::load (this=0x14, 
    __m=std::memory_order_acquire)
    at /usr/bin/../lib/gcc/i686-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/atomic_base.h:713
713		return __atomic_load_n(&_M_p, __m);
(gdb) bt
#0  0x0804bcad in std::__atomic_base<moodycamel::ConcurrentQueue<int, moodycamel::ConcurrentQueueDefaultTraits>::ProducerBase*>::load (this=0x14, 
    __m=std::memory_order_acquire)
    at /usr/bin/../lib/gcc/i686-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/atomic_base.h:713
#1  std::atomic<moodycamel::ConcurrentQueue<int, moodycamel::ConcurrentQueueDefaultTraits>::ProducerBase*>::load (this=0x14, __m=std::memory_order_acquire)
    at /usr/bin/../lib/gcc/i686-linux-gnu/6.3.0/../../../../include/c++/6.3.0/atomic:420
#2  0x0804ba15 in moodycamel::ConcurrentQueue<int, moodycamel::ConcurrentQueueDefaultTraits>::try_dequeue<int> (this=0x14, item=@0xb7be1298: -1212280144)
    at ./concurrentqueue.h:1048
#3  0x0804b958 in AZDS::CP::AbstractConnect<int, int, int>::operate (
    this=0x8062b28) at ./Pipeline.h:76
#4  0x080546dc in AZDS::CP::pipecore<int, int> (owner=0xbfffef10)
    at ./Pipeline.h:117
```

**Comment by Zenohate** [comment]
Nevermind, the debugger mislead me in thinking the problem was in the CQ by mistake.
Sorry to have bothered you ;-;

**Comment by cameron314** [comment]
No worries, glad you found the bug :-)
